config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: %i[index show new create update destroy edit] do
    resources :bookmarks, only: %i[new create]

  end

  resources :bookmarks, only: [:destroy, :new]

  resources :movies, only: %i[index show new create update destroy edit]



  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
  validates :overview, length: { maximum: 400 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end


# GET new
# assigns a new bookmark to @list (FAILED - 1)
# POST create
# with valid params
#   creates a new bookmark (FAILED - 2)
#   assigns a newly created bookmark as @bookmark (FAILED - 3)
#   redirects to the created list (FAILED - 4)
# with invalid params
#   assigns a newly created but unsaved bookmark as @bookmark (FAILED - 5)
#   re-renders the 'new' template or 'lists/show' (FAILED - 6)
# DELETE destroy
# deletes a bookmark (FAILED - 7)

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)

    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :picture_url)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movies = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save

    if @movie.save
      redirect_to movies_path, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(:rating)

    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "HOME", lists_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">


      </ul>
    </div>
  </div>
</div>


<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://i.ibb.co/HDdS5Sj/fundo-fotografico-tecido-sublimado-hollywood-400m-x-250m-D-NQ-NP-752726-MLB27858034276-072018-F.jpg')">

  <div class="container" style="height: 250px">
  </div>
</div>


<div class="my-bm-container">
  <h1>Create a new <strong>bookmark!</strong></h1>

  <div class="new-bookmark">
    <%= simple_form_for [@list, @bookmark] do |f| %>
    <div class="form-inputs">
      <%= f.input :comment %>
      <%= f.association :list %>
      <%= f.association :movie, collection: Movie.all.order(:title) %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-outline-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


</div>


    <%= yield %>


  </body>
</html>

app/views/lists/_form.html.erb
<div class="row justify-content-center">
  <div class="col-3">
    <h3>Add List</h3>
    <%= simple_form_for [list] do |f| %>
      <%= f.input :name %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/lists/_movie.html.erb
<div class="card-product">
<img src= <%= movie.poster_url %> >
  <div class="card-product-infos">
    <h3><strong><%= movie.title %> </strong> ⭐ <strong><%= movie.rating %></strong></h3>
    <p class="movie-overview"><%= movie.overview %><br></p>
    <p class="bookmark-comment"><strong>Bookmark: </strong><%= movie.bookmarks.last.comment %><br></p>

    <%= link_to "Delete",
        bookmark_path(movie.bookmarks.find_by(list: list)),
        method: :delete,
        data: { confirm: "Sure about it?" } %>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "HOME", lists_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <li class="nav-item">
          <%= link_to "Create Bookmark", new_list_bookmark_path(@list), class: "nav-link" %>
        </li>


        <li class="nav-item">
          <%= link_to "Delete List",
            list_path,
            method: :delete,
            data: { confirm: "Sure about it?" },
            class: "nav-link" %>
        </li>

      </ul>
    </div>
  </div>
</div>


<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.picture_url %>)">

  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="my-bm-container">
  <h1>Edit list</h1>

  <div class="new-bookmark">

    <div class="row justify-content-center">
      <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :picture_url %>
      <%= f.button :submit, class: 'btn btn-outline-dark' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "JULI's project", lists_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <li class="nav-item active">
          <%= link_to "New List",  new_list_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Movies", movies_path, class: "nav-link"  %>
        </li>

      </ul>
    </div>
  </div>
</div>

<div class="home-banner">
  <h1>Save any kind of movies</h1>
  <h3>Create a new list</h3>
</div>

<div class="container text-center ">
  <div class="row justify-content-center">
    <div class="col-6">

      <h1 style="padding: 30px">Lists</h1>

      <div class="container">
        <div class="row">

          <% @lists.each do |list| %>
          <div class="card-list col"
            style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.picture_url %>)">
            <%= link_to list.name, list_path(list) %>
          </div>
          <% end %>
          <div class="btn-index-fix-margin">
            <%= link_to 'New List', new_list_path, class: 'btn btn-outline-dark' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


      <div class="container">
        <div class="row">


<div class="container  ">
  <div class="row justify-content-center ">
    <div class="col-6">

app/views/lists/new.html.erb
<h1>New List</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :picture_url %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
  </div>
<% end  %>

app/views/lists/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "HOME", lists_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <li class="nav-item active">
          <%= link_to "Edit List", edit_list_path, class: "nav-link" %>
        </li>


        <li class="nav-item">
          <%= link_to "Create Bookmark", new_list_bookmark_path(@list), class: "nav-link" %>
        </li>


        <li class="nav-item">
          <%= link_to "Delete List",
            list_path,
            method: :delete,
            data: { confirm: "Sure about it?" },
            class: "nav-link" %>
        </li>

      </ul>
    </div>
  </div>
</div>






<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.picture_url %>)">

  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>


<div class="container">
  <div class="row">

    <% @list.movies.each do |movie| %>

    <div class="col"><%= render 'movie', movie: movie, list: @list %></div>

    <% end %>

  </div>
</div>

app/views/movies/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "HOME", lists_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <li class="nav-item active">
          <%= link_to "Add Movie",  new_movie_path, class: "nav-link" %>
        </li>



      </ul>
    </div>
  </div>
</div>



<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://i.ibb.co/HDdS5Sj/fundo-fotografico-tecido-sublimado-hollywood-400m-x-250m-D-NQ-NP-752726-MLB27858034276-072018-F.jpg')">

  <div class="container" style="height: 250px">
  </div>
</div>
<div class="container text-center ">
      <h1 style="padding: 50px">Movies</h1>
      </div>

<div class="container">
  <div class="row">

    <% @movies.each do |movie| %>
    <div class="card-product col-4">
      <img src=<%= movie.poster_url %>>
      <div class="card-product-infos">
        <h3><strong><%= movie.title %> </strong> ⭐ <strong><%= movie.rating %></strong></h3>
        <p class="movie-overview"><%= movie.overview %><br></p>
        <div class="my-link-to"><%= link_to "Delete",
            movie_path(movie[:id]),
            method: :delete,
            data: { confirm: "Sure about it?" } %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="btn-index-fix-margin">
    <%= link_to 'Add Movie', new_movie_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
</div>
</div>
</div>

app/views/movies/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "HOME", lists_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">


      </ul>
    </div>
  </div>
</div>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://i.ibb.co/HDdS5Sj/fundo-fotografico-tecido-sublimado-hollywood-400m-x-250m-D-NQ-NP-752726-MLB27858034276-072018-F.jpg')">

  <div class="container" style="height: 250px">
  </div>
</div>


<div class="my-bm-container">
<h1>New Movie</h1>
<%= simple_form_for(@movie) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :overview %>
    <%= f.input :poster_url %>
    <%= f.input :rating %>

  </div>
  <div class="form-actions" style="padding-bottom: 30px">
    <%= f.button :submit, class: 'btn btn-outline-dark' %>
  </div>
<% end  %>
  </div>
</div>